spring:
 application:
  name: open-api
 datasource:
   url: jdbc:mysql://localhost:3306/openapi?useSSL=false&serverTimezone=UTC
   username: root
   password: root
   driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080

# springdoc-openai 配置
springdoc:
  api-docs:
    # 是否开启接口文档
    enabled: true
    # OpenAPI文档的路径
    path: /api-docs
  swagger-ui:
    # swagger-ui路径
    path: /api.html
    # 持久化认证数据
    persistAuthorization: true
  info:
    # 标题
    title: 'API文档'
    # 描述
    description: '描述：API文档的详细信息'
    # 版本
    version: '版本号: 1.0.0'
  # 分组配置
  group-configs:
    - group: open-api
      packages-to-scan: com.xiaoman.openapi.controller


